apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: busybox-multi
  name: busybox-multi
spec:
  containers:
  - command:
    - /bin/sh
    - -c
    - echo hello; sleep 3600
    image: busybox
    name: busybox1
  - command:
    - /bin/sh
    - -c
    - echo hello; sleep 3600
    image: busybox
    name: busybox2
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
