apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: busybox
  name: busybox
spec:
  volumes:
    - name: basic
      emptyDir: {}
  containers:
  - command:
    - /bin/sh
    - -c
    - sleep 3600
    image: busybox
    name: busybox-1
    volumeMounts:
      - name: basic
        mountPath: /etc/foo
  - command:
    - /bin/sh
    - -c
    - sleep 3600
    image: busybox
    name: busybox-2
    volumeMounts:
      - name: basic
        mountPath: /etc/foo
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
