apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx-gpu
  name: nginx-gpu
spec:
  nodeSelector:
    acceleratoor: nvidia-tesla-p100
  containers:
  - image: nginx
    name: nginx-gpu
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
